- hosts: storage  #이미지 생성 및 사설저장소로 Push
  become: yes
  tasks:
    - name: Docker private registry 컨테이너 실행
      shell: |
        {% raw %}
        docker ps -a --format '{{.Names}}' | grep -w registry && docker rm -f registry || echo "registry not exists"
        docker run -d --name registry -p 5000:5000 --restart always registry:2
        {% endraw %}

    - name: 이미지 pull (공식 이미지)
      shell: |
        docker pull prom/prometheus:v3.2.1
        docker pull grafana/grafana:11.5.2
        docker pull quay.io/prometheus/node-exporter:v1.9.0
        docker pull gcr.io/cadvisor/cadvisor:v0.49.1

    - name: 사설 이미지 태그 지정
      shell: |
        docker tag prom/prometheus:v3.2.1 211.183.3.105:5000/myprome:v3.2.1
        docker tag grafana/grafana:11.5.2 211.183.3.105:5000/mygrafa:11.5.2
        docker tag quay.io/prometheus/node-exporter:v1.9.0 211.183.3.105:5000/mynode:v1.9.0
        docker tag gcr.io/cadvisor/cadvisor:v0.49.1 211.183.3.105:5000/mycad:v0.49.1

    - name: 이미지 push
      shell: |
        docker push 211.183.3.105:5000/myprome:v3.2.1
        docker push 211.183.3.105:5000/mygrafa:11.5.2
        docker push 211.183.3.105:5000/mynode:v1.9.0
        docker push 211.183.3.105:5000/mycad:v0.49.1



