- hosts: all        #server.lst의 모든 호스트에게 node-exporter/cadvisor 이미지 Pull      
  become: yes
  tasks:
    - name: pull node-exporter
      docker_image:
        name: 211.183.3.150:5000/mynode:v1.9.0
        source: pull

    - name: pull cadvisor 
      docker_image:
        name: 211.183.3.150:5000/mycad:v0.49.1
        source: pull

- hosts: manager    #매니저 노드에 prometheus/grafana 이미지 Pull
  become: yes
  tasks:
    - name: pull prometheus 
      docker_image:
        name: 211.183.3.150:5000/myprome:v3.2.1
        source: pull

    - name: pull grafana
      docker_image:
        name: 211.183.3.150:5000/mygrafa:11.5.2
        source: pull

