version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    networks:
      - net
    volumes:
       - ./prometheus.yml:/etc/prometheus/prometheus.yml  # 설정 파일 마운트
       - prometheus_data:/prometheus 
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

    ports:
      - target: 9090
        published: 9090
        mode: host

  grafana:
    image: grafana/grafana:latest
    networks:
      - net
    volumes:
      - grafana_data:/var/lib/grafana  # 데이터 저장용 볼륨
     
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
        
    ports:
      - target: 3000
        published: 3000
        mode: host


  node_exporter:
    image: prom/node-exporter:latest
    deploy:
      mode: global  # 모든 노드에서 실행
      restart_policy:
        condition: on-failure
    ports:
      - target: 9100
        published: 9100
        mode: host

    networks:
      - net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global  # 모든 노드에서 실행
      restart_policy:
        condition: on-failure
    ports:
      - target: 8080
        published: 8080
        mode: host

    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

    networks:
      - net

networks:
  net:
    driver: overlay
    attachable: true

volumes:
  prometheus_data:
  grafana_data:   
