- hosts: all
  become_user: root
  tasks:
    - name: node-exporter 이미지 pull
      docker_image:
        name: prom/node-exporter
        source: pull

    - name: cadvisor 이미지 pull
      docker_image:
        name: gcr.io/cadvisor/cadvisor:latest
        source: pull

- hosts: manager
  become_user: root
  tasks:
    - name: prometheus 이미지 pull
      docker_image:
        name: prom/prometheus
        source: pull

    - name: grafana 이미지 pull
      docker_image:
        name: grafana/grafana
        source: pull



