- name: Docker Swarm 실행 및 워커 조인
  hosts: 211.183.3.100  # 메인 매니저 IP 직접 지정
  become: true
  vars:
    manager_ip: "{{ inventory_hostname }}"

  tasks:
    - name: Docker Swarm 실행
      shell: docker swarm init --advertise-addr {{ manager_ip }}
      register: swarm_result
      failed_when: swarm_result.rc != 0 and 'already part of a swarm' not in swarm_result.stderr

    - name: 워커 토큰 가져오기
      shell: docker swarm join-token -q worker
      register: worker_token
      retries: 10
      delay: 2
      until: worker_token.rc == 0

    - name: worker_join.sh 생성 (조인 스크립트)
      copy:
        dest: /home/user1/worker_join.sh
        content: |
          #!/bin/bash
          docker swarm join --token {{ worker_token.stdout }} {{ manager_ip }}:2377
        owner: user1
        group: user1
        mode: '0755'

    - name: 조인 스크립트 배포 (worker 노드에게만)
      copy:
        src: /home/user1/worker_join.sh
        dest: /home/user1/worker_join.sh
        mode: '0755'
      delegate_to: "{{ item }}"
      loop: "{{ groups['nodes'] }}"

    - name: 조인 스크립트 실행 (worker 노드에서만)
      shell: bash /home/user1/worker_join.sh || true
      become: true
      delegate_to: "{{ item }}"
      loop: "{{ groups['nodes'] }}"

# 만약 worker 노드 중 매니저를 추가하고 싶다면 worker를 승격시킵니다.
# `docker node promote <승급시킬 노드 호스트명>`